# Generated by Django 5.2.4 on 2025-07-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="national_id",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
